# ebean configuration
ebean:
  dumpMetricsOnShutdown: true
  dumpMetricsOptions: loc,sql,hash
  ddl:
    generate: true
    run: true
  debug:
    sql: true
    lazyload: true
  logging: all

# database configuration
datasource:
  db:
    username: root
    password: 20260521
    platform: mariadb # sqlite, h2, postgres, mysql, oracle, sqlserver
    ddlMode: dropCreate # none | dropCreate | migrations
    dbName: conserjeria
    url: jdbc:mariadb://localhost:3306/conserjeria
